name: CI

on:
  push:
    branches:
      - main

jobs:
  ci:
    if: ${{ !contains(github.event.head_commit.message, '[skip') }}
    uses: efiand/site-core/.github/workflows/host-ci.yml@1.6.0
    with:
      test_command: npm test
      artifact_paths: public/
    secrets: inherit

  deploy:
    needs: ci
    if: ${{ !contains(github.event.head_commit.message, '[no-deploy]') && !contains(github.event.head_commit.message, '[WIP]') }}
    permissions:
      id-token: write
      pages: write
    uses: efiand/site-core/.github/workflows/deploy-github-pages.yml@1.6.0
    with:
      source_path: public
